# << Swami Shreeji >>
# @nishantpatel ; 18 Sep 2017
# k8s 101

apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec: 
  containers:
  - name: nginx
    image: nginx:1.13.5
    ports:
    - containerPort: 80