# << Swami Shreeji >>
# @nishantpatel ; 19 Sep 2017 
# k8s Tuts - Stateless app using a deployment

# Update a deployment by applying a new YAML
# Scale the app by applying a new YAML 

apiVersion: apps/v1beta1
kind: Deployment 
metadata: 
  name: nginx-deployment
spec: 
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx 
    spec:
      containers:
      - name: nginx 
        image: nginx:1.13
        ports:
        - containerPort: 80