# << Swami Shreeji >>
# @nishantpatel ; 19 Sep 2017
# k8s tutorial - PHP guestbook 

apiVersion: v1
kind: Service
metadata: 
  name: redis-master
  labels:
    app: redis
    role: master
    tier: backend
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector: 
    app: redis
    role: master
    tier: backend